# Generated by Django 3.0.5 on 2022-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('no_polisi', models.CharField(max_length=10)),
                ('warna', models.CharField(max_length=10)),
                ('merk', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=20)),
                ('tahun', models.DateField()),
                ('pajak', models.IntegerField(max_length=50)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
